# -*- coding: utf-8 -*-
"""02_pre_processing_norm_IL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xmjbUR8ybwjPSzyS6C74fJy1EziM3g1B

**PRE-PROCESSING: REINHARD NORMALIZATION**
"""

# INSTALLINGS

!pip install imagecodecs
!pip install histomicstk --find-links https://girder.github.io/large_image_wheels
!pip uninstall opencv-python-headless==4.5.5.62
!pip install opencv-python-headless==4.1.2.30
!pip install plotly==5.3.1

!pip install pyyaml==5.4.1

# LINKAGE TO GOOGLE DRIVE AND LIBRERIES IMPORTING

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import numpy as np
import plotly.express as px
import imagecodecs
import cv2

from matplotlib import pyplot as plt
from tqdm import tqdm
from skimage.io import imread, imshow, imsave
from skimage.transform import resize
from skimage.segmentation import mark_boundaries
from scipy import ndimage
from skimage.util import img_as_float,img_as_ubyte, crop
from skimage import exposure
from skimage.morphology import binary_dilation
from keras.utils.np_utils import to_categorical
from skimage import measure, morphology
from scipy.ndimage import median_filter

from skimage.color import rgb2hsv
from __future__ import print_function
import histomicstk as htk

# DATASET UNRAR: LOADING DATASET IN COLAB

!pip install unrar
!unrar x "drive/MyDrive/cytology challenge condivisa/00_DATASET/train.rar"     # unraring training set
!unrar x "drive/MyDrive/cytology challenge condivisa/00_DATASET/validation.rar"   # unraring validation set
!unrar x "drive/MyDrive/cytology challenge condivisa/00_DATASET/test.rar"         # unraring test set

# SETTINGS OF CURRENT PRE-PROCESSING

pre_proc_name = 'NORM_IL'  # name of current pre-processing <------------------------------- CHANGE HERE
rsz = 512  # resizing size (resize images to rsz x rsz) <-------------------------------- CHANGE HERE
NUM_CLASSES = 3 # number of classes choosen for the problem <---------------------------- CHANGE HERE

# LOAD RESIZED TRAINING SET AND VALIDATION SET

# load
images = np.load('drive/MyDrive/cytology challenge condivisa/01_PRE-PROCESSED/IL1.npz')  # images loading <--------------------------------------- CHANGE HERE
labels = np.load('drive/MyDrive/cytology challenge condivisa/01_PRE-PROCESSED/IL1_manual_mask_512x512.npz')  # manual annotations loading <-------- CHANGE HERE
X_tr = images['X_tr']
X_vl = images['X_vl']
Y_tr = labels['Y_tr']
Y_vl = labels['Y_vl']
images.close()
labels.close()
del images,labels

# REIHNARD NORMALIZATION


fig = px.imshow(X_tr[1:10], animation_frame=0, binary_string=True, labels=dict(x="normalized images - VLS",animation_frame="slice"))
fig.show()
img_ref = X_tr[1]


# fig = px.imshow(img_ref)
# fig.show()

mean_ref, std_ref = htk.preprocessing.color_conversion.lab_mean_std(img_ref)

for n in tqdm(range(len(X_tr)), total=len(X_tr)):

    # loading
    img = np.copy(X_tr[n])
    img_norm = htk.preprocessing.color_normalization.reinhard(img, mean_ref, std_ref)
    X_tr[n] = np.copy(img_norm)


fig = px.imshow(X_tr[1:30], animation_frame=0, binary_string=True, labels=dict(x="normalized images - TRS",animation_frame="slice"))
fig.show()

img = []
img_norm = []

for n in tqdm(range(len(X_vl)), total=len(X_vl)):

    # loading
    img = np.copy(X_vl[n])
    img_norm = htk.preprocessing.color_normalization.reinhard(img, mean_ref, std_ref)
    X_vl[n] = np.copy(img_norm)

fig = px.imshow(X_vl[1:10], animation_frame=0, binary_string=True, labels=dict(x="normalized images - VLS",animation_frame="slice"))
fig.show()

# SAVING PRE-PROCESSED

np.savez(os.path.join('drive/MyDrive/cytology challenge condivisa/01_PRE-PROCESSED',pre_proc_name),X_tr=X_tr,X_vl=X_vl)
#pre_proc_annotations_name = 'PRA_manual_mask_' + str(rsz) + 'x' + str(rsz)  # <------------------------------------------------- comment this line if preprocessed annotations of wanted size are already existing
#np.savez(os.path.join('drive/MyDrive/cytology challenge/01_PRE-PROCESSED',pre_proc_annotations_name),Y_tr=Y_tr,Y_vl=Y_vl)  # <-- comment this line if preprocessed annotations of wanted size are already existing